import { DOCUMENT } from "@angular/core";

export const Labels = {
    en: {
        PERSON: {
            PERSON: "Person",
            PERSONS: "Persons",
            ALL_PERSONS: "All Persons",
            ACTIVE_PERSONS: "Active Persons",
            ACTIVE_PRIVATE_PERSONS: "Active Private Persons",
            ACTIVE_PUBLIC_PERSONS: "Active Public Persons",
            ADD_PERSON: "Add Person",
            ENTER_PERSON_DETAILS: "Enter person details",
            PERSON_ID_DOCUMENTS: "ID Documents",
            ENTER_PERSON_ID_DOCUMENTS: "Enter person id document details",

            UPLOAD_DOCUMENT: "Upload Document",
            EDIT_DOCUMENT: "Edit Document",
            EDIT_PERSON: "Edit Person",
            VIEW_DOCUMENT: "View Document",
            DELETE_DOCUMENT: "Delete Document",
            DOCUMENT_TYPE: "Document Type",
            ID_NUMBER: "ID Number",
            PLACE_OF_ISSUE: "Place of Issue",
            OTHER_DOCUMENTS: "Other Documents",
            OTHER_DOCUMENT: "Other Document",
            ENTER_OTHER_DOCUMENTS: "Enter other document details...",
            DESCRIPTION: "Description",
            DOCUMENT_TYPE_REQUIRED: "Document Type is required",
            NATIONALITY_REQUIRED: "Nationality is required",
            PLACE_OF_ISSUE_REQUIRED: "Place of Issue is required",
            ID_NUMBER_REQUIRED: "Number is required",
            ENTER_ID_NUMBER: "Enter document number...",
            SELECT_ISSUE_DATE: "Select issue date...",
            SELECT_EXPIRY_DATE: "Select expiry date...",
            ISSUE_DATE_REQUIRED: "Issue Date is required",
            FILE_REQUIRED: "File is required",
            OR_DRAG_AND_DROP: "or drag and drop",
            REMOVE_ATTACHMENT: "Remove Attachment",
            PERSON_CREATED_SUCCESSFULLY: "Person Created Successfully",
            CAPACITIES_IN_COMPANIES: "Capacities In Companies",
            BOARD_MEMBERSHIP: "Board Membership",

            ACCOUNT_SIGNATORIES: "Account Signatories",
            ADD_ADDRESS: "Add Address",
            EDIT_ADDRESS: "Edit Address",
            PERSON_REQUIRED: "Person is required",
            PERSON_ENGLISH_NAME: "Person English Name",
            PERSON_ARABIC_NAME: "Person Arabic Name",
            PERSON_SHORT_NAME: "Person Short Name",
        },
        COMPANY: {
            COMPANY: "Company",
            CODE: "Code",
            SELECT_COMPANY_ACTIVITY: "Select Company Activity",
            COMPANY_NAME: "Company Name",
            ENTER_COMPANY_DETAILS: "Enter company details",
            PERSONS_IN_CHARGE: "Persons In Charge",
            ADD_PERSON_IN_CHARGE: "Add Person In Charge",
            STATUS: "Status",
            PRIVATE: "Private",
            ADD_NEW: "Add Company",
            ACTIVATE: "Activate",
            DEACTIVATE: "Deactivate",
            MARK_PUBLIC: "Mark Public",
            MARK_PRIVATE: "Mark Private",
            EXPORT_EXCEL: "Export to Excel",
            EXPORT_PDF: "Export to PDF",
            COMPANIES: "Companies",
            ALL_COMPANIES: "All Companies",
            REGISTRATIONS: "Registrations",
            BOARD_MEMBERSHIP: "Board Membership",
            EDIT_ACCOUNT_SIGNATORY: "Edit Account Signatory", // <-- Added
            ENTER_ACCOUNT_SIGNATORY_DETAILS: "Enter account signatory details", // <-- Added
            ACCOUNT_SIGNATORY: "Account Signatory",
            ACCOUNT_SIGNATORY_DATE: "Appointment Date",
            BOARD_MEMBER: "Board Member",
            ACCOUNT_SIGNATORIES: "Account Signatories",
            ACTIVE_COMPANIES: "Active Companies",
            SEARCH_ACTIVE_COMPANIES: "Search Active Companies",
            ACTIVE_PUBLIC_COMPANIES: "Active Public Companies",
            SEARCH_PUBLIC_COMPANIES: "Search Public Companies",
            ACTIVE_PRIVATE_COMPANIES: "Active Private Companies",
            SEARCH_PRIVATE_COMPANIES: "Search Private Companies",
            PUBLIC: "Public",
            EXPORT: "Export",
            ADVANCED_FILTER: "Advanced Filter",
            CAPITAL_AMOUNT: "Capital",
            TOTAL_SHARES: "Total Shares",
            NUMBER_OF_PARTNERS: "Number of Partners",
            TYPE: "Type",
            CLASS: "Class",
            LEGAL_FORM: "Legal Form",
            ACTIVITY: "Activity",
            CONTRACT_TYPE: "Contract Type",
            CONTRACTS: "Contracts",
            CONTRACT: "Contract",
            ADD_CONTRACT: "Add Contract",
            EDIT_CONTRACT: "Edit Contract",
            ENTER_CONTRACT_DETAILS: "Enter contract details",
            PLACE_OF_REGISTRATION: "Place of Registration",
            PLACE_OF_REGISTRATION_SUB: "Place of Registration Sub",
            REMINDER: "Reminder",
            INC_DATE: "Inc. Date",
            SHORT_NAME: "Short Name",
            FPC_CODE: "FPC Code",
            LICENSE_NUMBER: "License Number",
            ISSUE_DATE: "Issue Date",
            EXPIRY_DATE: "Expiry Date",
            NAME: "Name",
            DOCUMENT_DATE: "Document Date",
            COMMENCEMENT_DATE: "Commencement Date",
            DESCRIPTION: "Description",
            DESIGNATION: "Designation",
            FROM_AMOUNT: "From Amount",
            TO_AMOUNT: "To Amount",
            SHAREHOLDERS: "Shareholders",
            SHAREHOLDER: "Shareholder",
            ADD_SHAREHOLDER: "Add Shareholder",
            SHARE_PERCENT: "% of Shares",
            APPOINTMENT_DATE: "Appointment Date",
            CESSATION_DATE: "Cessation Date",
            ORG_CHART: "Org Chart",
            CHAMBER_OF_COMMERCE: "Chamber of Commerce",
            ADD_CHAMBER: "Add Chamber",
            LICENSES_AND_REGISTERS: "Licenses & Registers",
            ADD_LICENSE_OR_REGISTER: "Add License or Register",
            LICENSE_STATUS: "License Status",
            LICENSE_CLASSIFICATION: "Classification",
            ISSUE_DATE_REQUIRED: "Issue Date is required",
            EXPIRY_DATE_REQUIRED: "Expiry Date is required",
            ACTIVITIES: "Company Activities",
            ADD_ACTIVITY: "Add Activity",
            CAPITALS: "Company Capitals",
            ADD_CAPITAL: "Add Company Capital",
            NOMINAL_VALUE_OF_SHARE: "Nominal Value of Share",
            AUTHORIZED_CAPITAL_AMOUNT: "Authorized Capital Amount",
            PAID_CAPITAL_AMOUNT: "Paid Capital Amount",
            ISSUED_SHARES: "Issued Shares",
            CLASS_OF_SHARES: "Class of Shares",
            CCI_NUMBER: "CCI Number",
            CCI_ISSUE_DATE: "CCI Issue Date",
            CCI_ISSUE_DATE_REQUIRED: "CCI Issue Date is required",
            CCI_EXPIRY_DATE: "Expiry Date",
            CCI_USERNAME: "CCI Username",
            CCI_PASSWORD: "CCI Password",
            ADD_BOARD_MEMBER: "Add Board Member", // <-- Added
            BANK_ACCOUNTS: "Bank Accounts",           // <-- Added
            BANK_ACCOUNT: "Bank Account",           // <-- Added
            ADD_BANK_ACCOUNT: "Add Bank Account",     // <-- Added
            ADD_ACCOUNT_SIGNATORY: "Add Account Signatory", // <-- Added
            CAPITAL_CURRENCY: "Capital Currency", // <-- Added
            ENTER_COMPANY_EMAIL: "Enter company email",
            EDIT_PERSON_IN_CHARGE: "Edit Person In Charge",
            ENTER_PERSON_IN_CHARGE_DETAILS: "Enter Person In Charge Details",
            DESIGNATION_REQUIRED: "Designation is required",
            AUTHORITY_RULE: "Authority Rule",
            ENTER_COMPANY_PHONE_DETAILS: "Enter company phone details",
            EDIT_SHAREHOLDER: "Edit Shareholder",
            ENTER_SHAREHOLDER_DETAILS: "Enter shareholder details",
            COMPANY_REQUIRED: "Company is required",
            NUMBER_OF_SHARES: "Number of Shares",
            NUMBER_OF_SHARES_REQUIRED: "Number of Shares is required",
            EDIT_BOARD_MEMBER: "Edit Board Member", // <-- Added
            ENTER_BOARD_MEMBER_DETAILS: "Enter Board Member Details", 
            SIGNATORIES: "Signatories",
            BOARDS: "Boards",
            BOARD: "Board",
            ADD_BOARD: "Add Board",
            EDIT_BOARD: "Edit Board",

        },
        COMMON: {
            DOCUMENTS: "Documents",
            DESCRIPTION: "Description",
            NT_LOGIN: "NT Login",
            ADD_NEW_MENU_ITEM: "Add New Menu Item",
            NAME: "Name",
            ADD_GROUP_MENU: "Add Group Menu",
            EDIT_OTHER_DOCUMENT: "Edit Other Document",
            SELECT: "Select",
            NO_RESULTS_FOUND: "No results found",
            CONFIRM_DELETE: "Confirm Delete",
            PERSON: "Person",
            CREATE: "Create",
            COMPANY: "Company",
            EDIT_ID_DOCUMENT: "Edit ID Document",
            ADD_COMPANY: "Add Company",
            EMAIL_REQUIRED: "Email is required",
            PHONE_REQUIRED: "Phone is required",
            ADDRESS_REQUIRED: "Address is required",
            NO_FILE_SELECTED: "No file selected",
            UPLOAD_FILE: "Upload File",
            UPLOAD_FILES: "Upload Files",
            UPLOAD_DOCUMENT: "Upload Document",
            END_DATE: "End Date",
            VIEW_FILE: "View File",
            PHONE_TYPE: "Phone Type",
            PHONE_TYPE_REQUIRED: "Phone type is required",
            ID: "ID",
            ADD: "Add",
            EDIT: "Edit",
            UPDATE: "Update",
            DELETE: "Delete",
            FILTERS: "Filters",
            SEARCH: "Search",
            PRINT: "Print",
            SELECTED: "selected",
            ACTION: "Action",
            ACTIONS: "Actions",
            PRIMARY: "Primary",
            FILE_NAME: "File Name",
            ADD_USER: "Add User",
            START_DATE_REQUIRED: "Start Date is required",
            END_DATE_REQUIRED: "End Date is required",
            END_DATE_BEFORE_START_DATE: "End date cannot be before start date",
            SELECT_DATE: "Select Date",
            DATE_REQUIRED: "Date is required",
            ADD_USERS: "Add Users",
            EDIT_USER: "Edit User",
            USERS: "Users",
            ADD_MENUS: "Add Menus",
            SET_MENUS: "Set Menus",
            PUBLIC: "Public",
            PRIVATE: "Private",
            NEW: "New",
            ACTIVE: "Active",
            INACTIVE: "Inactive",
            IS_LD_STAFF: "Is Ld Staff",
            YES: "Yes",
            NO: "No",
            ALL: "All",
            EXPORT: "Export",
            ACTIVATE: "Activate",
            DEACTIVATE: "Deactivate",
            NATIONALITY: "Nationality",
            RECORDS_RETURNED: "Records has been returned",
            NO_RECORDS: "No records available",
            EDIT_COMPANY: "Edit Company",
            MORE_ACTIONS: "More Actions",
            REMINDER: "Reminder",
            INC_DATE: "Inc. Date",
            START_DATE: "Start Date",
            SHORT_NAME: "Short Name",
            FPC_CODE: "FPC Code",
            LICENSE_NUMBER: "License Number",
            ISSUE_DATE: "Issue Date",
            EXPIRY_DATE: "Expiry Date",
            MARK_PUBLIC: "Mark Public",
            MARK_PRIVATE: "Mark Private",
            OVERVIEW: "Overview",
            VIEW: "View",
            CONTACTS: "Contacts",
            ASSETS: "Assets",
            NOTES: "Notes",
            NOTES_REQUIRED: "Notes is required",
            NAME_EN: "Name En",
   
            NAME_AR: "Name Ar",
            SHOW: "Show",
            HIDE: "Hide",
            ADD_NOTE: "Add Note",
            EDIT_NOTE: "Edit Note",
            DELETE_NOTE: "Delete Note",
            DATE: "Date",
            STATUS: "Status",
            EMAIL_ADDRESSES: "Emails",
            EMAIL_ADDRESS: "Email",
            ADD_EMAIL: "Add Email",
            EDIT_EMAIL: "Edit Email",
            DELETE_EMAIL: "Delete Email",
            PHONE_NUMBERS: "Phones",
            PHONE_NUMBER: "Phone",
            ACCOUNT_SIGNATORIES: "Account Signatories",
            NT_LOGGIN: "NT Loggin",
            ADD_PHONE: "Add Phone",
            EDIT_PHONE: "Edit Phone",
            DELETE_PHONE: "Delete Phone",
            ADD_ADDRESS: "Add Address",
            EDIT_ADDRESS: "Edit Address",
            DELETE_ADDRESS: "Delete Address",
            ADDRESSES: "Addresses",
            CANCEL: "Cancel",
            SAVE: "Save",
            SHORT_NAME_REQUIRED: "Short Name is required",
            FIRST_NAME_AR_REQUIRED: "First Name (Arabic) is required",
            FIRST_NAME_EN_REQUIRED: "First Name (English) is required",
            LEGAL_ASSISTANCE_SYSTEM: "Legal Assistance System",
            NO_SPACES: "cannot contain spaces.",
            ADD_NAME_EN: "Add English Name",
            ADD_NAME_AR: "Add Arabic Name",
            ADD_SHORT_NAME: "Add Short Name",
            ADDRESS_LINE1: "Address Line 1",
            ADDRESS_LINE2: "Address Line 2",
            ADDRESS_LINE3: "Address Line 3",
            ADDRESS_LINE1_PLACEHOLDER: "Enter street address, building number...",
            ADDRESS_LINE2_PLACEHOLDER: "Enter apartment, suite, unit...",
            ADDRESS_LINE3_PLACEHOLDER: "Enter additional address details...",
            ADDRESS_LINE1_REQUIRED: "Address Line 1 is required",
            ADDRESS_LINE2_REQUIRED: "Address Line 2 is required",
            ADDRESS_LINE3_REQUIRED: "Address Line 3 is required",
            MASTER_SEARCH_PLACEHLDER: "Search persons, companies, real estates...",
            PO_BOX_NUMBER: "PO Box Number",
            EXPIRED: "Expired",
            PO_BOX_NUMBER_PLACEHOLDER: "Enter P.O. Box number...",
            PO_BOX_NUMBER_REQUIRED: "PO Box Number is required",
            CITIES: "Cities",
            DATE_OF_APPOINTMENT: "Appointment Date",
            RULE: "Rule",
            LOADING: "Loading...",                    // <-- Added
            OR_DRAG_AND_DROP: "or drag and drop",      // <-- Added
            FILE_REQUIRED: "File is required",
            ENTER_VALID_EMAIL: "Enter a valid email",
            APPOINTMENT_DATE_REQUIRED: "Appointment Date is required",
            PHONE_NUMBER_MIN_LENGTH: "Phone must be at least 6 characters long",
            PHONE_NUMBER_MAX_LENGTH: "Phone cannot be more than 14 characters long",
            DOWNLOAD: "Download",
            CLOSE: "Close",
            REGISTER_TYPE: "Register Type",
            REGISTER_NAME: "Register Name",
            REGISTER_CODE: "Register Code",
            REGISTER_TYPE_REQUIRED: "Register Type is required",
            BANK_NAME: "Bank Name",               // <-- Added
            BANK_NAME_REQUIRED: "Bank Name is required", // <-- Added
            ACCOUNT_NUMBER: "Account Number",         // <-- Added
            ACCOUNT_NUMBER_REQUIRED: "Account Number is required", // <-- Added
            BANK_ACCOUNT_DATE: "Bank Account Date", // <-- Added
            BANK_ACCOUNT_DATE_REQUIRED: "Bank Account Date is required", // <-- Added
            EDIT_BANK_ACCOUNT: "Edit Bank Account", // <-- Added
            ENTER_BANK_ACCOUNT_DETAILS: "Enter bank account details", // <-- Added
            ADD_BANK_ACCOUNT: "Add Bank Account", // <-- Added
            CESSATION_DATE_REQUIRED: "Cessation Date is required",
            TO_AMOUNT_REQUIRED: "To Amount is required",
            FROM_AMOUNT_REQUIRED: "From Amount is required",
            RULE_REQUIRED: "Rule is required",
            ENTER_ADDRESS_DETAILS: "Enter address details",
            ADDRESS_LINE_1: "Address Line 1",
            ADDRESS_LINE_2: "Address Line 2",
            ADDRESS_LINE_3: "Address Line 3",
            ADDRESS_LINE_1_REQUIRED: "Address Line 1 is required",
            DETAILS: "Details",
            COUNTRY: "Country",
            COUNTRY_REQUIRED: "Country is required",
            CITY: "City",
            CITY_REQUIRED: "City is required",
            ZONE: "Zone",
            PHONE_1: "Phone 1",
            PHONE_2: "Phone 2",
            PHONE_3: "Phone 3",
            FAX: "Fax",
            EMAIL_1: "Email 1",
            EMAIL_2: "Email 2",
            POSTAL_CODE: "Postal Code",
            ADDRESS: "Address",
            FIRST_NAME: "First Name",
            LAST_NAME: "Last Name",
            USERNAME: "Username",
            EMAIL: "Email",
            LOGIN_NAME: "Login Name",
            ADD_NEW_USER_GROUP: "Add New User Group",
            SEARCH_BY_NAME: "Search by name",
            CODE: "Code",
            NAME_REQUIRED: "Name is required",
            DESCRIPTION_REQUIRED: "Description is required",
            PHONE_INVALID: "Phone number must contain only digits (7-15 digits)",
            FAX_INVALID: "Fax number must contain only digits (7-15 digits)",
            EMAIL_INVALID: "Invalid email address",
            BEFORE_15_DAYS: "Before 15 days",
            BEFORE_30_DAYS: "Before 30 days",
            BEFORE_45_DAYS: "Before 45 days",
            AFTER_15_DAYS: "Within 15 days",
            AFTER_30_DAYS: "Within 30 days",
            AFTER_45_DAYS: "Within 45 days",
            ACTIVE_REMINDER: "Active Reminder",
            NOT_ACTIVE_REMINDER: "Not Active Reminder",
            LOAD_MORE: "Load more",
            TO_DO_LIST: "To-Do List",
            ALL_FILES: "All Files",
            ALLOWED_TYPES: "Allowed File Types",
            MAX_SIZE: "Max Size",
            PER_FILE: "per file",
            MULTIPLE_FILES: "Multiple Files",
            FILE_TOO_LARGE: "File is too large",
            FILES_TOO_LARGE: "Some files are too large",
            MAX_SIZE_ALLOWED: "Maximum size allowed is ",
            UPLOADED_FILES: "Uploaded Files",
            FILE: "File",
            PREVIEW: "Preview",
            REMOVE: "Remove",
            NO_FILES_UPLOADED: "No files uploaded",
            AMENDED: "Amended"
        },
        PROPERTY: {
            RELATION_REQUIRED: "Relation is required",
            REAL_EASTATES: "Real Estates",
            REAL_EASTATE: "Real Estate",
            ADD_NEW_PROPERTY: "Add New Property",
            OWNERS: "Owners",
            OWNER: "Owner",
            EDIT_PROPERTY: "Edit Property",
            ENTER_PROPERTY_DETAILS: "Enter Property Details",
            TYPE_OF_TITLE: "Type of Title",
            PROPERTY_TYPE: "Type",
            PROPERTY_PURPOSE: "Purpose",
            TYPE_OF_TITLE_REQUIRED: "Type of Title is required",
            PLOT: "Plot #",
            PLOT_F_AREA: "Plot Area(Sq F)",
            PLOT_M_AREA: "Plot Area(Sq M)",
            PROPERTY_F_AREA: "Property Area(Sq F)",
            PROPERTY_M_AREA: "Property Area(Sq M)",
            LOCATION_DETAILS: 'Details',
            SEARCH_BY_CODE: "Search by Code",
            LINKS: "Links",
            PROPERTY_LINK: "Property Link Value",
            LINK_REMARKS: "Property Link Remarks",
            OWNER_REMARKS: "Owner Remarks",
            PROPERTY_LINKS: "Property Links",
            ADD_PROPERTY_LINK: "Add Property Link",
            EDIT_PROPERTY_LINK: "Edit Property Link",
            ENTER_PROPERTY_LINK_DETAILS: "Enter Property Link Details",
            PROPERTY_LINK_REQUIRED: "Property Link is required",
            RELATION: "Relation",
            ADD_PROPERTY_OWNER: "Add Owner",
            EDIT_PROPERTY_OWNER: "Edit Owner",
            ENTER_PROPERTY_OWNER_DETAILS: "Enter Property Owner Details",
            REMARKS: "Remarks",
            PROPERTY_DOCUMENTS: "Property Documents",
            ADD_PROPERTY_DOCUMENT: "Add Property Document",
            EDIT_PROPERTY_DOCUMENT: "Edit Property Document",
            ENTER_PROPERTY_DOCUMENT_DETAILS: "Enter Property Document Details",
            DOCUMENT_TYPE: "Document Type",
            DOCUMENT_TYPE_REQUIRED: "Document Type is required",
            DOCUMENT: "Document",
            LEGAL_STATUS: "Legal Status",
            LEGAL_STATUS_REQUIRED: "Legal Status is required",
            ACTIVE_REAL_ESTATES: "Active Real Estates",
            ACTIVE_PRIVATE_REAL_ESTATES: "Active Private Real Estates",
            ACTIVE_PUBLIC_REAL_ESTATES: "Active Public Real Estates",
            ALL_REAL_ESTATES: "All Real Estates",
        },
        LAW_FIRM: {
            LAW_FIRMS: "Law Firms",
            LAW_FIRM: "Law Firm",
            ALL_LAW_FIRMS: "All Law Firms",
            ACTIVE_LAW_FIRMS: "Active Law Firms",
            ACTIVE_PRIVATE_LAW_FIRMS: "Active Private Law Firms",
            ACTIVE_PUBLIC_LAW_FIRMS: "Active Public Law Firms",
            ADD_LAW_FIRM: "Add Law Firm",
            ENTER_LAW_FIRM_DETAILS: "Enter Law Firm Details",
            EDIT_LAW_FIRM: "Edit Law Firm",
            BRANCH_NAME: "Branch Name",
            LAS_DATE: "LAS Date",
            EST_YEAR: "Est. Year",
            WEBSITE: "Website",
            EST_YEAR_MIN: "Minimum year is 1800",
            EST_YEAR_MAX: "Maximum year is " + (new Date().getFullYear()),
            BRANCHES: "Branches",
            COUNSLES: "Counsels",
            INVOICES: "Invoices",
            LAW_FIRM_PERSONS: "Contact Persons",
            LAW_FIRM_PERSON: "Contact Person",
            ADD_LAW_FIRM_PERSON: "Add Contact Person",
            EDIT_LAW_FIRM_PERSON: "Edit Contact Person",
            ENTER_LAW_FIRM_PERSON_DETAILS: "Enter Contact Person Details",
            PRACTICE: "Practice",
            PRACTICE_REQUIRED: "Practice is required",
            STAFF_LEVEL: "Staff Level",
            STAFF_LEVEL_REQUIRED: "Staff Level is required",
            LAW_FIRM_BRANCHES: "Branches",
            LAW_FIRM_BRANCH: "Branch",
            ADD_LAW_FIRM_BRANCH: "Add Branch",
            EDIT_LAW_FIRM_BRANCH: "Edit Branch",
            ENTER_LAW_FIRM_BRANCH_DETAILS: "Enter Branch Details",
            COUNSEL_NAME: "Counsel Name",
            COUNSEL_LEVEL: "Counsel Level",
            COUNSEL_RATE: "Rate",
            LAW_FIRM_COUNSELS: "Counsels",
            LAW_FIRM_COUNSEL: "Counsel",
            ADD_LAW_FIRM_COUNSEL: "Add Counsel",
            EDIT_LAW_FIRM_COUNSEL: "Edit Counsel",
            ENTER_LAW_FIRM_COUNSEL_DETAILS: "Enter Counsel Details",
            COUNSEL_LEVEL_REQUIRED: "Counsel Level is required",
            COUNSEL_RATE_REQUIRED: "Counsel Rate is required",
            LAW_FIRM_EXPERTISES: "Expertises",
            LAW_FIRM_EXPERTISE: "Expertise",
            ADD_LAW_FIRM_EXPERTISE: "Add Expertise",
            EDIT_LAW_FIRM_EXPERTISE: "Edit Expertise",
            ENTER_LAW_FIRM_EXPERTISE_DETAILS: "Enter Expertise Details",
            EXPERTISE_NAME: "Expertise Name",
            EXPERTISE_NAME_REQUIRED: "Expertise Name is required",
            EST_YEAR_DIGITS_ONLY: "Year must contain only digits",
            LAW_FIRM_REQUIRED: "Law Firm is required",
        },
        TRANSACTION: {
            ALL_TRANSACTIONS: "All Transactions",
            ACTIVE_TRANSACTIONS: "Active Transactions",
            ACTIVE_PRIVATE_TRANSACTIONS: "Active Private Transactions",
            ACTIVE_PUBLIC_TRANSACTIONS: "Active Public Transactions",
            TRANSACTION_NUMBER: "Transaction #",
            TRANSACTIONS: "Transactions",
            TRANSACTION: "Transaction",
            SUBJECT_TYPE: "Subject Type",
            ADD_TRANSACTION: "Add Transaction",
            ENTER_TRANSACTION_DETAILS: "Enter Transaction Details",
            EDIT_TRANSACTION: "Edit Transaction",
            TRANSACTION_DATE: "Transaction Date",
            TRANSACTION_DATE_REQUIRED: "Transaction Date is required",
            SUBJECT_TYPE_REQUIRED: "Subject Type is required",
            TRANSACTION_REGISTERS: "Registers",
            TRANSACTION_REGISTER: "Register",
            ADD_TRANSACTION_REGISTER: "Add Register",
            EDIT_TRANSACTION_REGISTER: "Edit Register",
            ENTER_TRANSACTION_REGISTER_DETAILS: "Enter Register Details",
            REGISTER_TYPE: "Register Type",
            REGISTER_TYPE_REQUIRED: "Register Type is required",
            REGISTER: "Register",
            REGISTER_REQUIRED: "Register is required",
            OTFS: "OTFs",
            ADD_OTF: "Add OTF",
            EDIT_OTF: "Edit OTF",
            ENTER_OTF_DETAILS: "Enter OTF Details",
            FOLLOW_UPS: "Follow Ups",
            FOLLOW_UP: "Follow Up",
            ADD_FOLLOW_UP: "Add Follow Up",
            EDIT_FOLLOW_UP: "Edit Follow Up",
            ENTER_FOLLOW_UP_DETAILS: "Enter Follow Up Details",
            DUE_DATE: "Due Date",
            CLOSED_DATE: "Closed Date",
            TIME: "Time",
            MINUTES: "Minutes",
            DUE_DATE_REQUIRED: "Due Date is required",
            FOLLOW_UP_FILES: "Follow Up Files",
            INVOICES: "Invoices",
            INVOICE: "Invoice",
            ADD_INVOICE: "Add Invoice",
            EDIT_INVOICE: "Edit Invoice",
            ENTER_INVOICE_DETAILS: "Enter Invoice Details",
            INVOICE_NUMBER: "Invoice #",
            INVOICE_DATE: "Invoice Date",
            AMOUNT: "Amount",
            PAID: "Paid",
            INVOICE_CURRENCY: "Invoice Currency",
            FILE_COUNT: "File Count",
            NO_FILES: "No Files",
            ACTION_STATUS: "Action Status",
        },
        FPC: {
            FPCS: "FPCs",
            FPC: "FPC",
            ALL_FPCS: "All FPCs",
            ADD_NEW_FPC: "Add New FPC",
            ENTER_FPC_DETAILS: "Enter FPC Details",
            EDIT_FPC: "Edit FPC",
            FPC_ODS: "FPC Original Documents",
            FPC_OD: "FPC Original Document",
            ADD_FPC_OD: "Add FPC Original Document",
            EDIT_FPC_OD: "Edit FPC Original Document",
            ENTER_FPC_OD_DETAILS: "Enter FPC Original Document Details",
            DOCUMENT_TYPE: "Document Type",
            ACTION_DATE: "Action Date",
            ACTION_DATE_REQUIRED: "Action Date is required",
            ACTION_TYPE: "Action Type",
            ACTION_TYPE_REQUIRED: "Action Type is required",
            FPC_OD_ACTIONS: "FPC Original Document Actions",
            FPC_OD_ACTION: "FPC Original Document Action",
            ADD_FPC_OD_ACTION: "Add FPC Original Document Action",
            EDIT_FPC_OD_ACTION: "Edit FPC Original Document Action",
            ENTER_FPC_OD_ACTION_DETAILS: "Enter FPC Original Document Action Details",
            LAST_ACTION_DATE: "Last Action Date",
            ACTIVE_PUBLIC_FPCS: "Active Public FPCs",
            ACTIVE_PRIVATE_FPCS: "Active Private FPCs",
            ACTIVE_FPCS: "Active FPCs"
        },
        DOCUMENT_TRACKING: {
            SEARCH: "Search by Code Or Reference Number",
            DOCUMENT_TRACKINGS: "Document Trackings",
            DOCUMENT_TRACKING: "Document Tracking",
            ALL_DOCUMENT_TRACKINGS: "All Document Trackings",
            ACTIVE_DOCUMENT_TRACKINGS: "Active Document Trackings",
            ADD_DOCUMENT_TRACKING: "Add Document Tracking",
            ENTER_DOCUMENT_TRACKING_DETAILS: "Enter Document Tracking Details",
            EDIT_DOCUMENT_TRACKING: "Edit Document Tracking",
            REFERENCE_NUMBER: "Ref. #",
            REGISTER_CODE: "Register Code",
            REGISTER_TYPE: "Register Type",
            DESCRIPTION: "Description",
            STATUS: "Status",
            REFERENCE_NUMBER_REQUIRED: "Reference Number is required",
            DOCUMENT_TRACKING_ACTIONS: "Document Tracking Actions",
            FOLLOW_UP: "Follow up",
            DOCUMENT_TRACKING_ACTION: "Document Tracking Action",
            ADD_DOCUMENT_TRACKING_ACTION: "Add Document Tracking Action",
            EDIT_DOCUMENT_TRACKING_ACTION: "Edit Document Tracking Action",
            ENTER_DOCUMENT_TRACKING_ACTION_DETAILS: "Enter Document Tracking Action Details",
            ACTION_DATE: "Date",
            ACTION_DATE_REQUIRED: "Date is required",
            ACTION_TYPE: "Type",
            ACTION_TYPE_REQUIRED: "Type is required",
            ACTION_DESCRIPTION: "Description",
            SENT_BY: "Sent By",
            SENT_BY_REQUIRED: "Sent By is required",
            FOLLOW_UPS: "Follow Ups",
            ADD_FOLLOW_UP: "Add Follow Up",
            EDIT_FOLLOW_UP: "Edit Follow Up",
            ENTER_FOLLOW_UP_DETAILS: "Enter Follow Up Details"
        },
        SETTINGS: {
            GROUPS: "Groups",
            GROUP: "Group",
            THE_GROUP: "The Group",
            IS_USER_IN_GROUP: "Is user in group?",
            MEMBERS: "Members",
            USERNAMES: "Usernames",
            USERNAME: "Username",
            USER_FULL_NAME: "User Full Name",
            MENUS: "Menus",
            MENU: "Menu",
            ACCESS: "Access",
            CAN_INSERT: "Can Insert?",
            CAN_UPDATE: "Can Update?",
            CAN_DELETE: "Can Delete?",
            ADMIN: "Admin?",
            IS_MENU_IN_GROUP: "Is menu in group?",
            GROUP_MENU_SETTINGS: "Group Menu Settings",
            GROUP_MENU_SUBTITLE: "Manage group menu settings.",
            INSERT_DESCRIPTION: "Allows user to add new records.",
            UPDATE_DESCRIPTION: "Allows user to edit existing records.",
            DELETE_DESCRIPTION: "Allows user to delete existing records.",
            ADMIN_DESCRIPTION: "Allows user to manage group menu settings."
        }
    },
    ar: {
        PERSON: {
            PERSON: "شخص",
            PERSONS: "الأشخاص",
            ALL_PERSONS: "جميع الأشخاص",
            ACTIVE_PERSONS: "الأشخاص النشطون",
            ACTIVE_PRIVATE_PERSONS: "الأشخاص الخاصون النشطون",
            ACTIVE_PUBLIC_PERSONS: "الأشخاص العامون النشطون",
            ADD_PERSON: "إضافة شخص",
            ENTER_PERSON_DETAILS: "أدخل تفاصيل الشخص",
            PERSON_ID_DOCUMENTS: "وثائق هوية الشخص",
            ENTER_PERSON_ID_DOCUMENTS: "أدخل وثائق هوية الشخص",
            UPLOAD_DOCUMENT: "رفع وثيقة",
            EDIT_DOCUMENT: "تعديل الوثيقة",
            EDIT_PERSON: "تعديل الشخص",
            VIEW_DOCUMENT: "عرض الوثيقة",
            DELETE_DOCUMENT: "حذف الوثيقة",
            DOCUMENT_TYPE: "نوع الوثيقة",
            ID_NUMBER: "رقم الهوية",
            PLACE_OF_ISSUE: "مكان الإصدار",
            OTHER_DOCUMENTS: "وثائق أخرى",
            OTHER_DOCUMENT: "وثيقة أخرى",
            ENTER_OTHER_DOCUMENTS: "أدخل تفاصيل الوثيقة الأخرى...",
            DESCRIPTION: "الوصف",
            DOCUMENT_TYPE_REQUIRED: "نوع الوثيقة مطلوب",
            NATIONALITY_REQUIRED: "الجنسية مطلوبة",
            PLACE_OF_ISSUE_REQUIRED: "مكان الإصدار مطلوب",
            ID_NUMBER_REQUIRED: "الرقم مطلوب",
            ENTER_ID_NUMBER: "أدخل رقم الوثيقة...",
            SELECT_ISSUE_DATE: "اختر تاريخ الإصدار...",
            SELECT_EXPIRY_DATE: "اختر تاريخ الانتهاء...",
            ISSUE_DATE_REQUIRED: "تاريخ الإصدار مطلوب",
            FILE_REQUIRED: "الملف مطلوب",
            OR_DRAG_AND_DROP: "أو اسحب وأسقط",
            REMOVE_ATTACHMENT: "حذف المرفق",
            PERSON_CREATED_SUCCESSFULLY: "تمت اضافة الشخص بنجاح",
            CAPACITIES_IN_COMPANIES: "الصفات في الشركات",
            DESIGNATION: "الصفة",
            BOARD_MEMBERSHIP: "عضوية مجلس الإدارة",
            ACCOUNT_SIGNATORIES: "المفوضون بالتوقيع",
            PERSON_REQUIRED: "الشخص مطلوب",
            ADD_ADDRESS: "إضافة العنوان",
            EDIT_ADDRESS: "تعديل العنوان",
            PERSON_ENGLISH_NAME: "اسم الشخص بالإنجليزية",
            PERSON_ARABIC_NAME: "اسم الشخص بالعربية",
            PERSON_SHORT_NAME: "الاسم المختصر للشخص",
        },

        COMPANY: {
            CODE: "الرمز",
            COMPANY: "شركة",
            NAME_EN: "الاسم بالإنجليزية",
            ENTER_COMPANY_DETAILS: "أدخل تفاصيل الشركة",
            NAME_AR: "الاسم بالعربية",
            PERSONS_IN_CHARGE: "الأشخاص المسؤولون",
            ADD_PERSON_IN_CHARGE: "إضافة شخص مسؤول",
            EDIT_PERSON_IN_CHARGE: "تعديل شخص مسؤول",
            COMPANY_NAME: "اسم الشركة",
            STATUS: "الحالة",
            PRIVATE: "خاص",
            ADD_NEW: "إضافة شركة جديدة",
            CONTRACTS: "عقود",
            CONTRACT: "عقد",
            ADD_CONTRACT: "اضافة عقد",
            EDIT_CONTRACT: "تعديل عقد",
            ENTER_CONTRACT_DETAILS: "أدخل تفاصيل العقد",
            ACTIVATE: "تفعيل",
            DEACTIVATE: "إلغاء التفعيل",
            MARK_PUBLIC: "تعيين كعام",
            MARK_PRIVATE: "تعيين كخاص",
            DESIGNATION: "الصفة",
            EXPORT_EXCEL: "تصدير إلى Excel",
            BOARD_MEMBERSHIP: "عضوية مجلس الإدارة",
            BOARD_MEMBER: "عضو مجلس إدارة",
            BOARDS: "المجالس الإدارية",
            BOARD: "مجلس الإدارة",
            ADD_BOARD: "إضافة مجلس إدارة",
            EDIT_BOARD: "تعديل مجلس الإدارة",
            REGISTRATIONS: "التسجيلات",
            ACCOUNT_SIGNATORIES: "المفوضون بالتوقيع",
            EXPORT_PDF: "تصدير إلى PDF",
            COMPANIES: "الشركات",
            ALL_COMPANIES: "جميع الشركات",
            MANAGE_COMPANIES: "إدارة الشركات",
            ADD_ACCOUNT_SIGNATORY: "إضافة مفوض بالتوقيع", // <-- Added
            EDIT_ACCOUNT_SIGNATORY: "تعديل مفوض بالتوقيع", // <-- Added
            ENTER_ACCOUNT_SIGNATORY_DETAILS: "أدخل تفاصيل المفوض بالتوقيع", // <-- Added
            ACCOUNT_SIGNATORY: "المفوض بالتوقيع",
            ACCOUNT_SIGNATORY_DATE: "تاريخ المفوض بالتوقيع",
            SELECT_COMPANY_ACTIVITY: "اختر نشاط الشركة",
            ACTIVE_COMPANIES: "الشركات النشطة",
            SEARCH_ACTIVE_COMPANIES: "بحث عن الشركات النشطة",
            ACTIVE_PUBLIC_COMPANIES: "الشركات العامة النشطة",
            SEARCH_PUBLIC_COMPANIES: "بحث عن الشركات العامة النشطة",
            ACTIVE_PRIVATE_COMPANIES: "الشركات الخاصة النشطة",
            SEARCH_PRIVATE_COMPANIES: "بحث عن الشركات الخاصة النشطة",
            SHAREHOLDER: "المساهم",
            PUBLIC: "عام",
            EXPORT: "تصدير",
            ADVANCED_FILTER: "تصفية متقدمة",
            CAPITAL_AMOUNT: "قيمة رأس المال",
            TOTAL_SHARES: "إجمالي الأسهم",
            NUMBER_OF_PARTNERS: "عدد الشركاء",
            TYPE: "النوع",
            CLASS: "الفئة",
            LEGAL_FORM: "الهيئة القانونية",
            ACTIVITY: "النشاط",
            CONTRACT_TYPE: "نوع العقد",
            PLACE_OF_REGISTRATION: "مكان التسجيل",
            PLACE_OF_REGISTRATION_SUB: "مكان التسجيل الفرعي",
            REMINDER: "تذكير",
            INC_DATE: "تاريخ التأسيس",
            SHORT_NAME: "الاسم المختصر",
            FPC_CODE: "رمز FPC",
            LICENSE_NUMBER: "رقم الرخصة",
            ISSUE_DATE: "تاريخ الإصدار",
            EXPIRY_DATE: "تاريخ الانتهاء",
            DOCUMENT_DATE: "تاريخ المستند",
            COMMENCEMENT_DATE: "تاريخ البدء",
            DESCRIPTION: "الوصف",
            FROM_AMOUNT: "من مبلغ",
            TO_AMOUNT: "إلى مبلغ",
            SHAREHOLDERS: "المساهمون",
            ADD_SHAREHOLDER: "إضافة مساهم",
            SHARE_PERCENT: "نسبة الأسهم",
            APPOINTMENT_DATE: "تاريخ التعيين",
            CESSATION_DATE: "تاريخ الانتهاء",
            ORG_CHART: "المخطط التنظيمي",
            CHAMBER_OF_COMMERCE: "غرفة التجارة",
            ADD_CHAMBER: "إضافة غرفة تجارة",
            LICENSES_AND_REGISTERS: "التراخيص والسجلات",
            ADD_LICENSE_OR_REGISTER: "إضافة ترخيص أو سجل",
            LICENSE_STATUS: "حالة الترخيص",
            LICENSE_CLASSIFICATION: "التصنيف",
            ISSUE_DATE_REQUIRED: "تاريخ الإصدار مطلوب",
            EXPIRY_DATE_REQUIRED: "تاريخ الانتهاء مطلوب",
            ACTIVITIES: "أنشطة الشركة",
            ADD_ACTIVITY: "إضافة نشاط",
            CAPITALS: "رأس مال الشركة",
            ADD_CAPITAL: "إضافة رأس مال الشركة",
            NOMINAL_VALUE_OF_SHARE: "القيمة الاسمية للسهم",
            AUTHORIZED_CAPITAL_AMOUNT: "رأس المال المصرح به",
            PAID_CAPITAL_AMOUNT: "رأس المال المدفوع",
            ISSUED_SHARES: "الأسهم المصدرة",
            CLASS_OF_SHARES: "فئة الأسهم",
            CCI_NUMBER: "رقم غرفة التجارة",
            CCI_ISSUE_DATE: "تاريخ إصدار غرفة التجارة",
            CCI_ISSUE_DATE_REQUIRED: "تاريخ إصدار غرفة التجارة مطلوب",
            CCI_EXPIRY_DATE: "تاريخ انتهاء غرفة التجارة",
            CCI_USERNAME: "اسم مستخدم غرفة التجارة",
            CCI_PASSWORD: "كلمة مرور غرفة التجارة",
            ADD_BOARD_MEMBER: "إضافة عضو مجلس إدارة", // <-- Added
            BANK_ACCOUNTS: "الحسابات البنكية",        // <-- Added
            ADD_BANK_ACCOUNT: "إضافة حساب بنكي",      // <-- Added
            CAPITAL_CURRENCY: "عملة رأس المال", // <-- Added
            ENTER_COMPANY_EMAIL: "أدخل بريد الشركة الإلكتروني",
            ENTER_PERSON_IN_CHARGE_DETAILS: "أدخل تفاصيل الشخص المسؤول",
            DESIGNATION_REQUIRED: "الصفة مطلوبة",
            AUTHORITY_RULE: "الصفة المخولة",
            ENTER_COMPANY_PHONE_DETAILS: "أدخل تفاصيل هاتف الشركة",
            EDIT_SHAREHOLDER: "تعديل المساهم",
            ENTER_SHAREHOLDER_DETAILS: "أدخل تفاصيل المساهم",
            COMPANY_REQUIRED: "الشركة مطلوبة",
            NUMBER_OF_SHARES: "عدد الأسهم",
            NUMBER_OF_SHARES_REQUIRED: "عدد الأسهم مطلوب",
            BANK_ACCOUNT: "الحساب البنكي",           // <-- Added
            EDIT_BOARD_MEMBER: "تعديل عضو مجلس الإدارة", // <-- Added
            ENTER_BOARD_MEMBER_DETAILS: "أدخل تفاصيل عضو مجلس الإدارة", // <-- Added
            ADDRESS: "العنوان",
            COUNTRY: "البلد",
            SIGNATORIES: "الموقعون",

        },
        COMMON: {
            DOCUMENTS: "الوثائق",
            NT_LOGIN: "تسجيل الدخول NT",
            DESCRIPTION: "الوصف",
            ADD_NEW_MENU_ITEM: "إضافة عنصر قائمة جديد",
            START_DATE_REQUIRED: "تاريخ البدء مطلوب",
            END_DATE_REQUIRED: "تاريخ الانتهاء مطلوب",
            END_DATE_BEFORE_START_DATE: "تاريخ الانتهاء لا يمكن أن يكون قبل تاريخ البدء",
            SELECT_DATE: "اختر التاريخ",
            NAME: "الاسم",
            ADD_GROUP_MENU: "إضافة مجموعة قائمة",
            EDIT_OTHER_DOCUMENT: "تعديل مستند آخر",
            SELECT: "تحديد",
            NO_RESULTS_FOUND: "لا توجد نتائج",
            CONFIRM_DELETE: "تأكيد الحذف",
            EDIT_ID_DOCUMENT: "تعديل وثيقة الهوية",
            PERSON: "شخص",
            COMPANY: "شركة",
            ADD_COMPANY: "إضافة شركة",
            LAST_NAME: "الاسم الأخير",
            EMAIL_REQUIRED: "البريد الإلكتروني مطلوب",
            PHONE_REQUIRED: "رقم الهاتف مطلوب",
            ADDRESS_REQUIRED: "العنوان مطلوب",
            DETAILS: "التفاصيل",
            NT_LOGGIN: "NT تسجيل الدخول",
            NO_FILE_SELECTED: "لم يتم اختيار ملف",
            UPLOAD_DOCUMENT: "رفع مستند",
            UPLOAD_FILE: "رفع ملف",
            UPLOAD_FILES: "رفع ملفات",
            VIEW_FILE: "عرض الملف",
            PHONE_TYPE: "نوع الهاتف",
            START_DATE: "تاريخ البدء",
            DATE_REQUIRED: "التاريخ مطلوب",
            END_DATE: "تاريخ الانتهاء",
            PHONE_TYPE_REQUIRED: "نوع الهاتف مطلوب",
            ID: "المعرف",
            ADD: "إضافة",
            EDIT: "تعديل",
            UPDATE: "تحديث",
            DELETE: "حذف",
            FILTERS: "الفلاتر",
            SEARCH: "بحث",
            PRINT: "طباعة",
            SELECTED: "مختار",
            ACTION: "إجراء",
            ACTIONS: "الإجراءات",
            PRIMARY: "أساسي",
            FILE_NAME: "اسم الملف",
            ADD_USER: "اضافة مستخدم",
            ADD_USERS: "اضافة المستخدمين",
            EDIT_USER: "تعديل المستخدم",
            USERS: "المستخدمون",
            CREATE: "إنشاء",
            MASTER_SEARCH_PLACEHLDER: "ابحث عن شخص أو شركة...",
            ADD_MENUS: "اضافة قائمة",
            SET_MENUS: "تعديل المجموعات",
            PUBLIC: "عام",
            EXPIRED: "منتهية",
            PRIVATE: "خاص",
            NEW: "جديد",
            ACTIVE: "نشط",
            INACTIVE: "غير نشط",
            IS_LD_STAFF: "هل موظف Ld",
            YES: "نعم",
            NO: "لا",
            ALL: "الكل",
            EXPORT: "تصدير",
            ACTIVATE: "تفعيل",
            DEACTIVATE: "إلغاء التفعيل",
            NATIONALITY: "الجنسية",
            RECORDS_RETURNED: "عدد السجلات المسترجعة",
            NO_RECORDS: "لا توجد سجلات",
            EDIT_COMPANY: "تعديل الشركة",
            MORE_ACTIONS: "مزيد من الإجراءات ",
            REMINDER: "تذكير",
            INC_DATE: "تاريخ التأسيس",
            FPC_CODE: "رمز FPC",
            LICENSE_NUMBER: "رقم الرخصة",
            ISSUE_DATE: "تاريخ الإصدار",
            EXPIRY_DATE: "تاريخ الانتهاء",
            MARK_PUBLIC: "تعيين كعام",
            MARK_PRIVATE: "تعيين كخاص",
            OVERVIEW: "نظرة عامة",
            CONTACTS: "جهات الاتصال",
            ASSETS: "الأصول",
            NOTES: "ملاحظات",
            NOTES_REQUIRED: "الملاحظات مطلوبة",
            SHORT_NAME: "الاسم المختصر",
            NAME_EN: "الاسم بالإنجليزية",
            NAME_AR: "الاسم بالعربية",
            SHOW: "إظهار",
            HIDE: "إخفاء",
            ADD_NOTE: "إضافة ملاحظة",
            EDIT_NOTE: "تعديل الملاحظة",
            DELETE_NOTE: "حذف الملاحظة",
            DATE: "التاريخ",
            STATUS: "الحالة",
            EMAIL_ADDRESSES: "عناوين البريد الإلكتروني",
            TO_AMOUNT_REQUIRED: "إلى مبلغ مطلوب",
            FROM_AMOUNT_REQUIRED: "من مبلغ مطلوب",
            EMAIL_ADDRESS: "عنوان البريد الإلكتروني",
            ADD_EMAIL: "إضافة بريد إلكتروني",
            EDIT_EMAIL: "تعديل البريد الإلكتروني",
            DELETE_EMAIL: "حذف البريد الإلكتروني",
            PHONE_NUMBERS: "أرقام الهواتف",
            PHONE_NUMBER: "رقم الهاتف",
            ADD_PHONE: "إضافة هاتف",
            EDIT_PHONE: "تعديل الهاتف",
            DELETE_PHONE: "حذف الهاتف",
            ADD_ADDRESS: "إضافة عنوان",
            EDIT_ADDRESS: "تعديل العنوان",
            DELETE_ADDRESS: "حذف العنوان",
            ADDRESSES: "العناوين",
            CANCEL: "إلغاء",
            SAVE: "حفظ",
            SHORT_NAME_REQUIRED: "الاسم المختصر مطلوب",
            FIRST_NAME_AR_REQUIRED: "الاسم الأول (بالعربية) مطلوب",
            FIRST_NAME_EN_REQUIRED: "الاسم الأول (بالإنجليزية) مطلوب",
            ADD_NAME_EN: "إضافة الاسم بالإنجليزية",
            ADD_NAME_AR: "إضافة الاسم بالعربية",
            ADD_SHORT_NAME: "إضافة الاسم المختصر",
            NO_SPACES: "لا يمكن أن يحتوي على مسافات.",
            CITIES: "المدن",
            ADDRESS_LINE1: "سطر العنوان 1",
            ADDRESS_LINE2: "سطر العنوان 2",
            ADDRESS_LINE3: "سطر العنوان 3",
            ADDRESS_LINE1_PLACEHOLDER: "أدخل عنوان الشارع، رقم المبنى...",
            ADDRESS_LINE2_PLACEHOLDER: "أدخل الشقة، الجناح، الوحدة...",
            ADDRESS_LINE3_PLACEHOLDER: "أدخل تفاصيل إضافية للعنوان...",
            ADDRESS_LINE1_REQUIRED: "سطر العنوان 1 مطلوب",
            ADDRESS_LINE2_REQUIRED: "سطر العنوان 2 مطلوب",
            ADDRESS_LINE3_REQUIRED: "سطر العنوان 3 مطلوب",
            PO_BOX_NUMBER: "رقم صندوق البريد",
            PO_BOX_NUMBER_PLACEHOLDER: "أدخل رقم صندوق البريد...",
            PO_BOX_NUMBER_REQUIRED: "رقم صندوق البريد مطلوب",
            LEGAL_ASSISTANCE_SYSTEM: "نظام المساعدة القانونية",
            DATE_OF_APPOINTMENT: "تاريخ التعيين",
            RULE: "الدور",
            VIEW: "عرض",
            LOADING: "جاري التحميل...",               // <-- Added
            OR_DRAG_AND_DROP: "أو اسحب وأسقط",      // <-- Added
            FILE_REQUIRED: "الملف مطلوب",
            ENTER_VALID_EMAIL: "أدخل بريد إلكتروني صالح",
            APPOINTMENT_DATE_REQUIRED: "تاريخ التعيين مطلوب",
            PHONE_NUMBER_MIN_LENGTH: "رقم الهاتف يجب أن يكون 6 أحرف على الأقل",
            PHONE_NUMBER_MAX_LENGTH: "رقم الهاتف لا يمكن أن يتجاوز 14 حرفًا",
            DOWNLOAD: "تنزيل",
            CLOSE: "إغلاق",
            ADDRESS: "عنوان",
            REGISTER_TYPE: "نوع السجل",
            REGISTER_NAME: "اسم السجل",
            REGISTER_CODE: "رمز السجل",
            REGISTER_TYPE_REQUIRED: "نوع السجل مطلوب",
            BANK_NAME: "اسم البنك",               // <-- Added
            BANK_NAME_REQUIRED: "اسم البنك مطلوب", // <-- Added
            ACCOUNT_NUMBER: "رقم الحساب",         // <-- Added
            ACCOUNT_NUMBER_REQUIRED: "رقم الحساب مطلوب", // <-- Added
            BANK_ACCOUNT_DATE: "تاريخ الحساب البنكي", // <-- Added
            BANK_ACCOUNT_DATE_REQUIRED: "تاريخ الحساب البنكي مطلوب", // <-- Added
            EDIT_BANK_ACCOUNT: "تعديل حساب البنك", // <-- Added
            ENTER_BANK_ACCOUNT_DETAILS: "أدخل تفاصيل حساب البنك", // <-- Added
            ADD_BANK_ACCOUNT: "إضافة حساب بنكي", // <-- Added
            CESSATION_DATE_REQUIRED: "تاريخ الانتهاء مطلوب",
            RULE_REQUIRED: "الدور مطلوب",
            ENTER_ADDRESS_DETAILS: "أدخل تفاصيل العنوان",
            ADDRESS_LINE_1: "العنوان 1",
            ADDRESS_LINE_2: "العنوان 2",
            ADDRESS_LINE_3: "العنوان 3",
            ADDRESS_LINE_1_REQUIRED: "العنوان 1 مطلوب",
            COUNTRY: "الدولة",
            COUNTRY_REQUIRED: "الدولة مطلوبة",
            PHONE_1: "الهاتف 1",
            PHONE_2: "الهاتف 2",
            PHONE_3: "الهاتف 3",
            FAX: "فاكس",
            EMAIL_1: "البريد الإلكتروني 1",
            EMAIL_2: "البريد الإلكتروني 2",
            CITY: "المدينة",
            CITY_REQUIRED: "المدينة مطلوبة",
            ZONE: "المنطقة",
            POSTAL_CODE: "الرمز البريدي",
            FIRST_NAME: "الاسم الأول",
            USERNAME: "اسم المستخدم",
            EMAIL: "البريد الإلكتروني",
            LOGIN_NAME: "اسم الدخول",
            ADD_NEW_USER_GROUP: "إضافة مجموعة مستخدمين جديدة",
            SEARCH_BY_NAME: "البحث بالاسم",
            CODE: "الرمز",
            NAME_REQUIRED: "الاسم مطلوب",
            DESCRIPTION_REQUIRED: "الوصف مطلوب",
            PHONE_INVALID: "يجب أن يحتوي رقم الهاتف على أرقام فقط (من 7 إلى 15 رقمًا)",
            FAX_INVALID: "يجب أن يحتوي رقم الفاكس على أرقام فقط (من 7 إلى 15 رقمًا)",
            EMAIL_INVALID: "عنوان البريد الإلكتروني غير صالح",
            BEFORE_15_DAYS: "قبل 15 يومًا",
            BEFORE_30_DAYS: "قبل 30 يومًا",
            BEFORE_45_DAYS: "قبل 45 يومًا",
            AFTER_15_DAYS: "خلال 15 يومًا",
            AFTER_30_DAYS: "خلال 30 يومًا",
            AFTER_45_DAYS: "خلال 45 يومًا",
            ACTIVE_REMINDER: "تذكير نشط",
            NOT_ACTIVE_REMINDER: "تذكير غير نشط",
            LOAD_MORE: "تحميل المزيد",
            TO_DO_LIST: "قائمة المهام",
            ALL_FILES: "جميع الملفات",
            ALLOWED_TYPES: "أنواع الملفات المسموح بها",
            MAX_SIZE: "الحد الأقصى لحجم الملف",
            PER_FILE: "لكل ملف",
            TOTAL_SIZE: "الحجم الإجمالي",
            MULTIPLE_FILES: "ملفات متعددة",
            FILE_TOO_LARGE: "الملف كبير جدًا",
            FILES_TOO_LARGE: "الملفات كبيرة جدًا",
            MAX_SIZE_ALLOWED: "الحد الأقصى المسموح به هو ",
            UPLOADED_FILES: "الملفات المرفوعة",
            FILE: "ملف",
            PREVIEW: "معاينة",
            REMOVE: "إزالة",
            NO_FILES_UPLOADED: "لم يتم رفع أي ملفات",
            AMENDED: "تم التعديل",
        },
        PROPERTY: {
            RELATION_REQUIRED: "العلاقة مطلوبة",
            REAL_EASTATES: "العقارات",
            REAL_EASTATE: "عقار",
            ACTIVE_REAL_ESTATES: "العقارات النشطة",
            ACTIVE_PRIVATE_REAL_ESTATES: "العقارات الخاصة النشطة",
            ACTIVE_PUBLIC_REAL_ESTATES: "العقارات العامة النشطة",
            ADD_NEW_PROPERTY: "إضافة عقار جديد",
            EDIT_PROPERTY: "تعديل العقار",
            OWNERS: "المالكون",
            ENTER_PROPERTY_DETAILS: "أدخل تفاصيل العقار",
            TYPE_OF_TITLE: "نوع الملكية",
            PROPERTY_TYPE: "نوع العقار",
            PROPERTY_PURPOSE: "غرض العقار",
            TYPE_OF_TITLE_REQUIRED: "نوع الملكية مطلوب",
            PLOT: "قطعة أرض",
            PLOT_F_AREA: "مساحة القطعة (قدم مربع)",
            PLOT_M_AREA: "مساحة القطعة (متر مربع)",
            PROPERTY_F_AREA: "مساحة العقار (قدم مربع)",
            PROPERTY_M_AREA: "مساحة العقار (متر مربع)",
            LOCATION_DETAILS: 'تفاصيل الموقع',
            SEARCH_BY_CODE: "البحث بالرمز",
            LINKS: "الروابط",
            OWNER: "المالك",
            PROPERTY_LINK: "رابط العقار",
            PROPERTY_LINKS: "روابط العقار",
            LINK_REMARKS: "ملاحظات الرابط",
            ADD_PROPERTY_LINK: "إضافة رابط عقار",
            EDIT_PROPERTY_LINK: "تعديل رابط العقار",
            ENTER_PROPERTY_LINK_DETAILS: "أدخل تفاصيل رابط العقار",
            PROPERTY_LINK_REQUIRED: "رابط العقار مطلوب",
            RELATION: "العلاقة",
            ADD_PROPERTY_OWNER: "إضافة مالك عقار",
            EDIT_PROPERTY_OWNER: "تعديل مالك العقار",
            ENTER_PROPERTY_OWNER_DETAILS: "أدخل تفاصيل مالك العقار",
            REMARKS: "ملاحظات",
            PROPERTY_DOCUMENTS: "وثائق العقار",
            ADD_PROPERTY_DOCUMENT: "إضافة وثيقة عقار",
            EDIT_PROPERTY_DOCUMENT: "تعديل وثيقة عقار",
            ENTER_PROPERTY_DOCUMENT_DETAILS: "أدخل تفاصيل وثيقة العقار",
            DOCUMENT_TYPE: "نوع الوثيقة",
            DOCUMENT_TYPE_REQUIRED: "نوع الوثيقة مطلوب",
            DOCUMENT: "الوثيقة",
            LEGAL_STATUS: "الحالة القانونية",
            LEGAL_STATUS_REQUIRED: "الحالة القانونية مطلوبة",
            OWNER_REMARKS: "ملاحظات المالك",
            

        },
        LAW_FIRM: {
            LAW_FIRMS: "مكاتب المحاماة",
            LAW_FIRM: "مكتب المحاماة",
            ALL_LAW_FIRMS: "جميع مكاتب المحاماة",
            ACTIVE_LAW_FIRMS: "مكاتب المحاماة النشطة",
            ACTIVE_PRIVATE_LAW_FIRMS: "مكاتب المحاماة الخاصة النشطة",
            ACTIVE_PUBLIC_LAW_FIRMS: "مكاتب المحاماة العامة النشطة",
            ADD_LAW_FIRM: "إضافة مكتب محاماة",
            ENTER_LAW_FIRM_DETAILS: "أدخل تفاصيل مكتب المحاماة",
            EDIT_LAW_FIRM: "تعديل مكتب المحاماة",
            BRANCH_NAME: "اسم الفرع",
            LAS_DATE: "تاريخ نظام المساعدة القانونية",
            EST_YEAR: "سنة التأسيس",
            WEBSITE: "الموقع الإلكتروني",
            EST_YEAR_MIN: "الحد الأدنى للسنة هو 1800",
            EST_YEAR_MAX: "الحد الأقصى للسنة هو " + (new Date().getFullYear()),
            BRANCHES: "الفروع",
            COUNSLES: "المستشارون",
            INVOICES: "الفواتير",
            LAW_FIRM_PERSONS: "الأشخاص المعنيون",
            LAW_FIRM_PERSON: "الشخص المعني",
            ADD_LAW_FIRM_PERSON: "إضافة شخص معني",
            EDIT_LAW_FIRM_PERSON: "تعديل الشخص المعني",
            ENTER_LAW_FIRM_PERSON_DETAILS: "أدخل تفاصيل الشخص المعني",
            PRACTICE: "الممارسة",
            PRACTICE_REQUIRED: "الممارسة مطلوبة",
            STAFF_LEVEL: "مستوى الموظف",
            STAFF_LEVEL_REQUIRED: "مستوى الموظف مطلوب",
            LAW_FIRM_BRANCHES: "الفروع",
            LAW_FIRM_BRANCH: "فرع",
            ADD_LAW_FIRM_BRANCH: "إضافة فرع",
            EDIT_LAW_FIRM_BRANCH: "تعديل فرع",
            ENTER_LAW_FIRM_BRANCH_DETAILS: "أدخل تفاصيل الفرع",
            COUNSEL_NAME: "اسم المستشار",
            COUNSEL_LEVEL: "مستوى المستشار",
            COUNSEL_RATE: "المعدل",
            LAW_FIRM_COUNSELS: "المستشارون",
            LAW_FIRM_COUNSEL: "مستشار",
            ADD_LAW_FIRM_COUNSEL: "إضافة مستشار",
            EDIT_LAW_FIRM_COUNSEL: "تعديل مستشار",
            ENTER_LAW_FIRM_COUNSEL_DETAILS: "أدخل تفاصيل المستشار",
            COUNSEL_LEVEL_REQUIRED: "مستوى المستشار مطلوب",
            COUNSEL_RATE_REQUIRED: "معدل المستشار مطلوب",
            LAW_FIRM_EXPERTISES: "الخبرات",
            LAW_FIRM_EXPERTISE: "خبرة",
            ADD_LAW_FIRM_EXPERTISE: "إضافة خبرة",
            EDIT_LAW_FIRM_EXPERTISE: "تعديل خبرة",
            ENTER_LAW_FIRM_EXPERTISE_DETAILS: "أدخل تفاصيل الخبرة",
            EXPERTISE_NAME: "اسم الخبرة",
            EXPERTISE_NAME_REQUIRED: "اسم الخبرة مطلوب",
            EST_YEAR_DIGITS_ONLY: "السنة يجب أن تحتوي على أرقام فقط",
            LAW_FIRM_REQUIRED: "مكتب المحاماة مطلوب",
        },
        TRANSACTION: {
            TRANSACTIONS: "المعاملات",
            TRANSACTION: "معاملة",
            SUBJECT_TYPE: "نوع الموضوع",
            ADD_TRANSACTION: "إضافة معاملة",
            ENTER_TRANSACTION_DETAILS: "أدخل تفاصيل المعاملة",
            TRANSACTION_NUMBER: "رقم المعاملة",
            EDIT_TRANSACTION: "تعديل المعاملة",
            ALL_TRANSACTIONS: "جميع المعاملات",
            ACTIVE_TRANSACTIONS: "المعاملات النشطة",
            ACTIVE_PRIVATE_TRANSACTIONS: "المعاملات الخاصة النشطة",
            ACTIVE_PUBLIC_TRANSACTIONS: "المعاملات العامة النشطة",
            TRANSACTION_DATE: "تاريخ المعاملة",
            TRANSACTION_DATE_REQUIRED: "تاريخ المعاملة مطلوب",
            SUBJECT_TYPE_REQUIRED: "نوع الموضوع مطلوب",
            TRANSACTION_REGISTERS: "سجلات المعاملات",
            TRANSACTION_REGISTER: "سجل المعاملة",
            ADD_TRANSACTION_REGISTER: "إضافة سجل معاملة",
            EDIT_TRANSACTION_REGISTER: "تعديل سجل معاملة",
            ENTER_TRANSACTION_REGISTER_DETAILS: "أدخل تفاصيل سجل المعاملة",
            REGISTER_TYPE: "نوع السجل",
            REGISTER_TYPE_REQUIRED: "نوع السجل مطلوب",
            REGISTER: "سجل",
            REGISTER_REQUIRED: "السجل مطلوب",
            OTFS: "OTFs",
            FOLLOW_UPS: "متابعات",
            FOLLOW_UP: "متابعة",
            ADD_FOLLOW_UP: "إضافة متابعة",
            EDIT_FOLLOW_UP: "تعديل متابعة",
            ENTER_FOLLOW_UP_DETAILS: "أدخل تفاصيل المتابعة",
            DUE_DATE: "تاريخ الاستحقاق",
            CLOSED_DATE: "تاريخ الإغلاق",
            TIME: "الوقت",
            MINUTES: "الدقائق",
            DUE_DATE_REQUIRED: "تاريخ الاستحقاق مطلوب",
            FOLLOW_UP_FILES: "ملفات المتابعة",
            INVOICES: "الفواتير",
            INVOICE: "فاتورة",
            ADD_INVOICE: "إضافة فاتورة",
            EDIT_INVOICE: "تعديل فاتورة",
            ENTER_INVOICE_DETAILS: "أدخل تفاصيل الفاتورة",
            INVOICE_NUMBER: "رقم الفاتورة",
            INVOICE_DATE: "تاريخ الفاتورة",
            AMOUNT: "المبلغ",
            PAID: "مدفوع",
            INVOICE_CURRENCY: "عملة الفاتورة",
            FILE_COUNT: "عدد الملفات",
            NO_FILES: "لا توجد ملفات",
            ADD_OTF: "إضافة OTF",
            EDIT_OTF: "تعديل OTF",
            ENTER_OTF_DETAILS: "أدخل تفاصيل OTF",
            ACTION_STATUS: "حالة الإجراء",
        },
        FPC: {
            FPC: "FPC",
            FPCS: "FPCs",
            ALL_FPCS: "جميع FPCs",
            ADD_NEW_FPC: "إضافة FPC جديد",
            ENTER_FPC_DETAILS: "أدخل تفاصيل FPC",
            EDIT_FPC: "تعديل FPC",
            FPC_ODS: "وثائق FPC الأصلية",
            FPC_OD: "وثيقة FPC الأصلية",
            ADD_FPC_OD: "إضافة وثيقة FPC الأصلية",
            EDIT_FPC_OD: "تعديل وثيقة FPC الأصلية",
            ENTER_FPC_OD_DETAILS: "أدخل تفاصيل وثيقة FPC الأصلية",
            DOCUMENT_TYPE: "نوع الوثيقة",
            ACTION_DATE: "تاريخ الإجراء",
            ACTION_DATE_REQUIRED: "تاريخ الإجراء مطلوب",
            ACTION_TYPE: "نوع الإجراء",
            ACTION_TYPE_REQUIRED: "نوع الإجراء مطلوب",
            FPC_OD_ACTIONS: "إجراءات وثيقة FPC الأصلية",
            FPC_OD_ACTION: "إجراء وثيقة FPC الأصلية",
            ADD_FPC_OD_ACTION: "إضافة إجراء وثيقة FPC الأصلية",
            EDIT_FPC_OD_ACTION: "تعديل إجراء وثيقة FPC الأصلية",
            ENTER_FPC_OD_ACTION_DETAILS: "أدخل تفاصيل إجراء وثيقة FPC الأصلية",
            LAST_ACTION_DATE: "اخر تاريخ اجراء",
            ACTIVE_PUBLIC_FPCS: "FPCs النشطة العامة",
            ACTIVE_PRIVATE_FPCS: "FPCs الخاصة النشطة",
            ACTIVE_FPCS: "FPCs النشطة"
        },
        DOCUMENT_TRACKING: {
            SEARCH: "البحث بالرمز أو رقم المرجع",
            DOCUMENT_TRACKINGS: "تتبع الوثائق",
            DOCUMENT_TRACKING: "تتبع الوثيقة",
            ALL_DOCUMENT_TRACKINGS: "جميع تتبع الوثائق",
            ACTIVE_DOCUMENT_TRACKINGS: "تتبع الوثائق النشط",
            ADD_DOCUMENT_TRACKING: "إضافة تتبع الوثيقة",
            ENTER_DOCUMENT_TRACKING_DETAILS: "أدخل تفاصيل تتبع الوثيقة",
            EDIT_DOCUMENT_TRACKING: "تعديل تتبع الوثيقة",
            REFERENCE_NUMBER: "رقم المرجع",
            REGISTER_CODE: "رمز السجل",
            REGISTER_TYPE: "نوع السجل",
            DESCRIPTION: "الوصف",
            STATUS: "الحالة",
            REFERENCE_NUMBER_REQUIRED: "رقم المرجع مطلوب",
            DOCUMENT_TRACKING_ACTIONS: "إجراءات تتبع الوثائق",
            DOCUMENT_TRACKING_ACTION: "إجراء تتبع الوثيقة",
            ADD_DOCUMENT_TRACKING_ACTION: "إضافة إجراء تتبع الوثيقة",
            EDIT_DOCUMENT_TRACKING_ACTION: "تعديل إجراء تتبع الوثيقة",
            ENTER_DOCUMENT_TRACKING_ACTION_DETAILS: "أدخل تفاصيل إجراء تتبع الوثيقة",
            ACTION_DATE: "تاريخ الإجراء",
            FOLLOW_UPS: "المتابعات",
            ACTION_DATE_REQUIRED: "تاريخ الإجراء مطلوب",
            ACTION_TYPE: "نوع الإجراء",
            ACTION_TYPE_REQUIRED: "نوع الإجراء مطلوب",
            ACTION_DESCRIPTION: "وصف الإجراء",
            SENT_BY: "تم إرساله بواسطة",
            SENT_BY_REQUIRED: "المرسل مطلوب",
            FOLLOW_UP: "متابعة",
            ADD_FOLLOW_UP: "إضافة متابعة",
            EDIT_FOLLOW_UP: "تعديل المتابعة",
            ENTER_FOLLOW_UP_DETAILS: "ادخل متابعة التفاصيل"
        },
        SETTINGS: {
            GROUPS: "المجموعات",
            GROUP: "مجموعة",
            THE_GROUP: "المجموعة",
            IS_USER_IN_GROUP: "هل المستخدم في المجموعة؟",
            MEMBERS: "الأعضاء",
            USERNAMES: "أسماء المستخدمين",
            USERNAME: "اسم المستخدم",
            USER_FULL_NAME: "الاسم الكامل للمستخدم",
            MENUS: "القوائم",
            MENU: "القائمة",
            ACCESS: "الوصول",
            CAN_INSERT: "يمكن الإدراج؟",
            CAN_UPDATE: "يمكن التحديث؟",
            CAN_DELETE: "يمكن الحذف؟",
            ADMIN: "مدير؟",
            IS_MENU_IN_GROUP: "هل القائمة في المجموعة؟",
            GROUP_MENU_SETTINGS: "إعدادات قائمة المجموعة",
            GROUP_MENU_SUBTITLE: "إدارة إعدادات قائمة المجموعة.",
            INSERT_DESCRIPTION: "يسمح للمستخدم بإضافة سجلات جديدة.",
            UPDATE_DESCRIPTION: "يسمح للمستخدم بتعديل السجلات الموجودة.",
            DELETE_DESCRIPTION: "يسمح للمستخدم بحذف السجلات.",
            ADMIN_DESCRIPTION: "يسمح للمستخدم بإدارة إعدادات قائمة المجموعة."
        }
    }
} as const;
