export const Labels = {
    en: {
        PERSON: {
            PERSONS: "Persons",
            ALL_PERSONS: "All Persons",
            ACTIVE_PERSONS: "Active Persons",
            ACTIVE_PRIVATE_PERSONS: "Active Private Persons",
            ACTIVE_PUBLIC_PERSONS: "Active Public Persons",
            ADD_PERSON: "Add Person",
            ENTER_PERSON_DETAILS: "Enter person details",
            PERSON_ID_DOCUMENTS: "Person ID Documents",
            UPLOAD_DOCUMENT: "Upload Document",
            EDIT_DOCUMENT: "Edit Document",
            EDIT_PERSON: "Edit Person",
            VIEW_DOCUMENT: "View Document",
            DELETE_DOCUMENT: "Delete Document",
            DOCUMENT_TYPE: "Document Type",
            ID_NUMBER: "ID Number",
            PLACE_OF_ISSUE: "Place of Issue",
            OTHER_DOCUMENTS: "Other Documents",
            DESCRIPTION: "Description",
            DOCUMENT_TYPE_REQUIRED: "Document Type is required",
            NATIONALITY_REQUIRED: "Nationality is required",
            PLACE_OF_ISSUE_REQUIRED: "Place of Issue is required",
            ID_NUMBER_REQUIRED: "Number is required",
            ENTER_ID_NUMBER: "Enter document number...",
            SELECT_ISSUE_DATE: "Select issue date...",
            SELECT_EXPIRY_DATE: "Select expiry date...",
            ISSUE_DATE_REQUIRED: "Issue Date is required",
            FILE_REQUIRED: "File is required",
            OR_DRAG_AND_DROP: "or drag and drop",
            REMOVE_ATTACHMENT: "Remove Attachment",
            PERSON_CREATED_SUCCESSFULLY: "Person Created Successfully",
            CAPACITIES_IN_COMPANIES: "Capacities In Companies",
            BOARD_MEMBERSHIP: "Board Membership",
            ACCOUNT_SIGNATORIES: "Account Signatories",
            ADD_ADDRESS: "Add Address",
            EDIT_ADDRESS: "Edit Address",
        },

        COMPANY: {
            CODE: "Code",
            SELECT_COMPANY_ACTIVITY: "Select Company Activity",
            COMPANY_NAME: "Company Name",
            ENTER_COMPANY_DETAILS: "Enter company details",
            PERSONS_IN_CHARGE: "Persons In Charge",
            ADD_PERSON_IN_CHARGE: "Add Person In Charge",
            STATUS: "Status",
            PRIVATE: "Private",
            ADD_NEW: "Add New Company",
            ACTIVATE: "Activate",
            DEACTIVATE: "Deactivate",
            MARK_PUBLIC: "Mark as Public",
            MARK_PRIVATE: "Mark as Private",
            EXPORT_EXCEL: "Export to Excel",
            EXPORT_PDF: "Export to PDF",
            COMPANIES: "Companies",
            ALL_COMPANIES: "All Companies",
            REGISTRATIONS: "Registrations",
            BOARD_MEMBERSHIP: "Board Membership",
            ACCOUNT_SIGNATORIES: "Account Signatories",
            ACTIVE_COMPANIES: "Active Companies",
            SEARCH_ACTIVE_COMPANIES: "Search Active Companies",
            ACTIVE_PUBLIC_COMPANIES: "Active Public Companies",
            SEARCH_PUBLIC_COMPANIES: "Search Public Companies",
            ACTIVE_PRIVATE_COMPANIES: "Active Private Companies",
            SEARCH_PRIVATE_COMPANIES: "Search Private Companies",
            PUBLIC: "Public",
            EXPORT: "Export",
            ADVANCED_FILTER: "Advanced Filter",
            CAPITAL_AMOUNT: "Capital Amount",
            TOTAL_SHARES: "Total Shares",
            NUMBER_OF_PARTNERS: "Number of Partners",
            TYPE: "Type",
            CLASS: "Class",
            LEGAL_FORM: "Legal Form",
            ACTIVITY: "Activity",
            CONTRACT_TYPE: "Contract Type",
            PLACE_OF_REGISTRATION: "Place of Registration",
            PLACE_OF_REGISTRATION_SUB: "Place of Registration Sub",
            REMINDER: "Reminder",
            INC_DATE: "Inc. Date",
            SHORT_NAME: "Short Name",
            FPC_CODE: "FPC Code",
            LICENSE_NUMBER: "License Number",
            ISSUE_DATE: "Issue Date",
            EXPIRY_DATE: "Expiry Date",
            NAME: "Name",
            DOCUMENT_DATE: "Document Date",
            COMMENCEMENT_DATE: "Commencement Date",
            DESCRIPTION: "Description",
            DESIGNATION: "Designation",
            FROM_AMOUNT: "From Amount",
            TO_AMOUNT: "To Amount",
            SHAREHOLDERS: "Shareholders",
            ADD_SHAREHOLDER: "Add Shareholder",
            SHARE_PERCENT: "% of Shares",
            APPOINTMENT_DATE: "Date of Appointment",
            CESSATION_DATE: "Date of Cessation",
            ORG_CHART: "Org Chart",
            CHAMBER_OF_COMMERCE: "Chamber Of Commerce",
            ADD_CHAMBER: "Add Chamber",
            LICENSES_AND_REGISTERS: "Licenses & Registers",
            ADD_LICENSE_OR_REGISTER: "Add License or Register",
            LICENSE_STATUS: "License Status",
            LICENSE_CLASSIFICATION: "Classification",
            ISSUE_DATE_REQUIRED: "Issue Date is required",
            EXPIRY_DATE_REQUIRED: "Expiry Date is required",
            ACTIVITIES: "Company Activities",
            ADD_ACTIVITY: "Add Activity",
            CAPITALS: "Company Capitals",
            ADD_CAPITAL: "Add Company Capital",
            NOMINAL_VALUE_OF_SHARE: "Nominal Value of Share",
            AUTHORIZED_CAPITAL_AMOUNT: "Authorized Capital Amount",
            PAID_CAPITAL_AMOUNT: "Paid Capital Amount",
            ISSUED_SHARES: "Issued Shares",
            CLASS_OF_SHARES: "Class Of Shares",
            CCI_NUMBER: "CCI Number",
            CCI_ISSUE_DATE: "CCI Issue Date",
            CCI_ISSUE_DATE_REQUIRED: "CCI Issue Date is required",
            CCI_EXPIRY_DATE: "CCI Expiry Date",
            CCI_USERNAME: "CCI Username",
            CCI_PASSWORD: "CCI Password",
            CONTRACTS: "Company Contracts",         // <-- Added
            ADD_CONTRACT: "Add Contract",           // <-- Added
            ADD_BOARD_MEMBER: "Add Board Member", // <-- Added
            BANK_ACCOUNTS: "Bank Accounts",           // <-- Added
            ADD_BANK_ACCOUNT: "Add Bank Account",     // <-- Added
            ADD_ACCOUNT_SIGNATORY: "Add Account Signatory", // <-- Added
            CAPITAL_CURRENCY: "Capital Currency", // <-- Added

        },
        COMMON: {
            PERSON: "Person",
            COMPANY: "Company",
            ADD_COMPANY: "Add Company",
            EMAIL_REQUIRED: "Email is required",
            PHONE_REQUIRED: "Phone number is required",
            ADDRESS_REQUIRED: "Address is required",
            NO_FILE_SELECTED: "No file selected",
            UPLOAD_FILE: "Upload File",
            UPLOAD_DOCUMENT: "Upload Document",
            VIEW_FILE: "View File",
            PHONE_TYPE: "Phone Type",
            PHONE_TYPE_REQUIRED: "Phone type is required",
            ID: "ID",
            ADD: "Add",
            EDIT: "Edit",
            UPDATE: "Update",
            DELETE: "Delete",
            FILTERS: "Filters",
            SEARCH: "Search",
            PRINT: "Print",
            SELECTED: "selected",
            ACTION: "Action",
            ACTIONS: "Actions",
            PRIMARY: "Primary",
            FILE_NAME: "File Name",
            ADD_USER: "Add User",
            ADD_USERS: "Add Users",
            ADD_MENUS: "Add Menus",
            SET_MENUS: "Set Menus",
            PUBLIC: "Public",
            PRIVATE: "Private",
            NEW: "New",
            ACTIVE: "Active",
            INACTIVE: "Inactive",
            IS_LD_STAFF: "Is Ld Staff",
            YES: "Yes",
            NO: "No",
            ALL: "All",
            EXPORT: "Export",
            ACTIVATE: "Activate",
            DEACTIVATE: "Deactivate",
            NATIONALITY: "Nationality",
            RECORDS_RETURNED: "Records has been returned",
            NO_RECORDS: "No records available",
            EDIT_COMPANY: "Edit Company",
            MORE_ACTIONS: "More Actions",
            REMINDER: "Reminder",
            INC_DATE: "Inc. Date",
            SHORT_NAME: "Short Name",
            FPC_CODE: "FPC Code",
            LICENSE_NUMBER: "License Number",
            ISSUE_DATE: "Issue Date",
            EXPIRY_DATE: "Expiry Date",
            MARK_PUBLIC: "Mark as Public",
            MARK_PRIVATE: "Mark as Private",
            OVERVIEW: "Overview",
            VIEW: "View",
            CONTACTS: "Contacts",
            ASSETS: "Assets",
            NOTES: "Notes",
            NAME_EN: "English Name",
            NAME_AR: "Arabic Name",
            SHOW: "Show",
            HIDE: "Hide",
            ADD_NOTE: "Add Note",
            EDIT_NOTE: "Edit Note",
            DELETE_NOTE: "Delete Note",
            DATE: "Date",
            STATUS: "Status",
            EMAIL_ADDRESSES: "Email Addresses",
            EMAIL_ADDRESS: "Email Address",
            ADD_EMAIL: "Add Email",
            EDIT_EMAIL: "Edit Email",
            DELETE_EMAIL: "Delete Email",
            PHONE_NUMBERS: "Phone Numbers",
            PHONE_NUMBER: "Phone Number",
            ACCOUNT_SIGNATORIES: "Account Signatories",
            ADD_PHONE: "Add Phone",
            EDIT_PHONE: "Edit Phone",
            DELETE_PHONE: "Delete Phone",
            ADD_ADDRESS: "Add Address",
            EDIT_ADDRESS: "Edit Address",
            DELETE_ADDRESS: "Delete Address",
            ADDRESSES: "Addresses",
            CANCEL: "Cancel",
            SAVE: "Save",
            SHORT_NAME_REQUIRED: "Short Name is required",
            FIRST_NAME_AR_REQUIRED: "First Name (Arabic) is required",
            FIRST_NAME_EN_REQUIRED: "First Name (English) is required",
            NO_SPACES: "cannot contain spaces.",
            ADD_NAME_EN: "Add English Name",
            ADD_NAME_AR: "Add Arabic Name",
            ADD_SHORT_NAME: "Add Short Name",
            ADDRESS_LINE1: "Address Line 1",
            ADDRESS_LINE2: "Address Line 2",
            ADDRESS_LINE3: "Address Line 3",
            ADDRESS_LINE1_PLACEHOLDER: "Enter street address, building number...",
            ADDRESS_LINE2_PLACEHOLDER: "Enter apartment, suite, unit...",
            ADDRESS_LINE3_PLACEHOLDER: "Enter additional address details...",
            ADDRESS_LINE1_REQUIRED: "Address Line 1 is required",
            ADDRESS_LINE2_REQUIRED: "Address Line 2 is required",
            ADDRESS_LINE3_REQUIRED: "Address Line 3 is required",
            PO_BOX_NUMBER: "PO Box Number",
            EXPIRED: "Expired",
            PO_BOX_NUMBER_PLACEHOLDER: "Enter P.O. Box number...",
            PO_BOX_NUMBER_REQUIRED: "PO Box Number is required",
            CITIES: "Cities",
            DATE_OF_APPOINTMENT: "Date of Appointment",
            RULE: "Rule",
            LOADING: "Loading...",                    // <-- Added
            NOTE: "Note",
            NO_RESULTS_FOUND: "No results found",
            CONFIRM_DELETE: "Confirm Delete",
            CONFIRM: "Confirm",
            CLOSE: "Close",
            SUBMIT: "Submit",
            OK: "OK",
            SEARCH_BY_NAME: "Search by name",
            ADD_NEW_USER_GROUP: "Add New User Group",
            ADD_NEW_MENU_ITEM: "Add New Menu Item",
            ADD_GROUP_MENU: "Add Group Menu",
            EDIT_OTHER_DOCUMENT: "Edit Other Document",
            EDIT_ID_DOCUMENT: "Edit ID Document",
            USERNAME: "Username",
            LOGIN_NAME: "Login Name",
            NT_LOGIN: "NT Login",
            EMAIL: "Email",
            FIRST_NAME: "First Name",
            LAST_NAME: "Last Name",
            NAME: "Name",
            DESCRIPTION: "Description",
            SELECT: "Select",
            HOME: "Home",
            DASHBOARD: "Dashboard",
            SETTINGS: "Settings",
            USERS: "Users",
            GROUPS: "Groups",
            MENUS: "Menus",
            REPORTS: "Reports",
            USER_MANAGEMENT: "User Management",
            GROUP_MANAGEMENT: "Group Management",
            MENU_MANAGEMENT: "Menu Management",
            DYNAMIC_LISTS: "Dynamic Lists",
            USER_GROUPS: "User Groups",
            GROUP_MENUS: "Group Menus",
        },
    },
    ar: {
        PERSON: {
            PERSONS: "الأشخاص",
            ALL_PERSONS: "جميع الأشخاص",
            ACTIVE_PERSONS: "الأشخاص النشطون",
            ACTIVE_PRIVATE_PERSONS: "الأشخاص الخاصون النشطون",
            ACTIVE_PUBLIC_PERSONS: "الأشخاص العامون النشطون",
            ADD_PERSON: "إضافة شخص",
            ENTER_PERSON_DETAILS: "أدخل تفاصيل الشخص",
            PERSON_ID_DOCUMENTS: "وثائق هوية الشخص",
            UPLOAD_DOCUMENT: "رفع وثيقة",
            EDIT_DOCUMENT: "تعديل الوثيقة",
            EDIT_PERSON: "تعديل الشخص",
            VIEW_DOCUMENT: "عرض الوثيقة",
            DELETE_DOCUMENT: "حذف الوثيقة",
            DOCUMENT_TYPE: "نوع الوثيقة",
            ID_NUMBER: "رقم الهوية",
            PLACE_OF_ISSUE: "مكان الإصدار",
            OTHER_DOCUMENTS: "وثائق أخرى",
            DESCRIPTION: "الوصف",
            DOCUMENT_TYPE_REQUIRED: "نوع الوثيقة مطلوب",
            NATIONALITY_REQUIRED: "الجنسية مطلوبة",
            PLACE_OF_ISSUE_REQUIRED: "مكان الإصدار مطلوب",
            ID_NUMBER_REQUIRED: "الرقم مطلوب",
            ENTER_ID_NUMBER: "أدخل رقم الوثيقة...",
            SELECT_ISSUE_DATE: "اختر تاريخ الإصدار...",
            SELECT_EXPIRY_DATE: "اختر تاريخ الانتهاء...",
            ISSUE_DATE_REQUIRED: "تاريخ الإصدار مطلوب",
            FILE_REQUIRED: "الملف مطلوب",
            OR_DRAG_AND_DROP: "أو اسحب وأسقط",
            REMOVE_ATTACHMENT: "حذف المرفق",
            PERSON_CREATED_SUCCESSFULLY: "تمت اضافة الشخص بنجاح",
            CAPACITIES_IN_COMPANIES: "الصفات في الشركات",
            DESIGNATION: "الصفة",
            BOARD_MEMBERSHIP: "عضوية مجلس الإدارة",
            ACCOUNT_SIGNATORIES: "المفوضون بالتوقيع",
        },

        COMPANY: {
            CODE: "الرمز",
            NAME_EN: "الاسم بالإنجليزية",
            ENTER_COMPANY_DETAILS: "أدخل تفاصيل الشركة",
            NAME_AR: "الاسم بالعربية",
            PERSONS_IN_CHARGE: "الأشخاص المسؤولون",
            ADD_PERSON_IN_CHARGE: "إضافة شخص مسؤول",
            COMPANY_NAME: "اسم الشركة",
            STATUS: "الحالة",
            PRIVATE: "خاص",
            ADD_NEW: "إضافة شركة جديدة",
            ACTIVATE: "تفعيل",
            DEACTIVATE: "إلغاء التفعيل",
            MARK_PUBLIC: "تعيين كعام",
            MARK_PRIVATE: "تعيين كخاص",
            DESIGNATION: "الصفة",
            EXPORT_EXCEL: "تصدير إلى Excel",
            BOARD_MEMBERSHIP: "عضوية مجلس الإدارة",
            REGISTRATIONS: "التسجيلات",
            ACCOUNT_SIGNATORIES: "المفوضون بالتوقيع",
            EXPORT_PDF: "تصدير إلى PDF",
            COMPANIES: "الشركات",
            ALL_COMPANIES: "جميع الشركات",
            MANAGE_COMPANIES: "إدارة الشركات",
            ADD_ACCOUNT_SIGNATORY: "إضافة مفوض بالتوقيع", // <-- Added
            SELECT_COMPANY_ACTIVITY: "اختر نشاط الشركة",
            ACTIVE_COMPANIES: "الشركات النشطة",
            SEARCH_ACTIVE_COMPANIES: "بحث عن الشركات النشطة",
            ACTIVE_PUBLIC_COMPANIES: "الشركات العامة النشطة",
            SEARCH_PUBLIC_COMPANIES: "بحث عن الشركات العامة النشطة",
            ACTIVE_PRIVATE_COMPANIES: "الشركات الخاصة النشطة",
            SEARCH_PRIVATE_COMPANIES: "بحث عن الشركات الخاصة النشطة",
            PUBLIC: "عام",
            EXPORT: "تصدير",
            ADVANCED_FILTER: "تصفية متقدمة",
            CAPITAL_AMOUNT: "قيمة رأس المال",
            TOTAL_SHARES: "إجمالي الأسهم",
            NUMBER_OF_PARTNERS: "عدد الشركاء",
            TYPE: "النوع",
            CLASS: "الفئة",
            LEGAL_FORM: "الهيئة القانونية",
            ACTIVITY: "النشاط",
            CONTRACT_TYPE: "نوع العقد",
            PLACE_OF_REGISTRATION: "مكان التسجيل",
            PLACE_OF_REGISTRATION_SUB: "مكان التسجيل الفرعي",
            REMINDER: "تذكير",
            INC_DATE: "تاريخ التأسيس",
            SHORT_NAME: "الاسم المختصر",
            FPC_CODE: "رمز FPC",
            LICENSE_NUMBER: "رقم الرخصة",
            ISSUE_DATE: "تاريخ الإصدار",
            EXPIRY_DATE: "تاريخ الانتهاء",
            NAME: "الاسم",
            DOCUMENT_DATE: "تاريخ المستند",
            COMMENCEMENT_DATE: "تاريخ البدء",
            DESCRIPTION: "الوصف",
            FROM_AMOUNT: "من مبلغ",
            TO_AMOUNT: "إلى مبلغ",
            SHAREHOLDERS: "المساهمون",
            ADD_SHAREHOLDER: "إضافة مساهم",
            SHARE_PERCENT: "نسبة الأسهم",
            APPOINTMENT_DATE: "تاريخ التعيين",
            CESSATION_DATE: "تاريخ الانتهاء",
            ORG_CHART: "المخطط التنظيمي",
            CHAMBER_OF_COMMERCE: "غرفة التجارة",
            ADD_CHAMBER: "إضافة غرفة تجارة",
            LICENSES_AND_REGISTERS: "التراخيص والسجلات",
            ADD_LICENSE_OR_REGISTER: "إضافة ترخيص أو سجل",
            LICENSE_STATUS: "حالة الترخيص",
            LICENSE_CLASSIFICATION: "التصنيف",
            ISSUE_DATE_REQUIRED: "تاريخ الإصدار مطلوب",
            EXPIRY_DATE_REQUIRED: "تاريخ الانتهاء مطلوب",
            ACTIVITIES: "أنشطة الشركة",
            ADD_ACTIVITY: "إضافة نشاط",
            CAPITALS: "رأس مال الشركة",
            ADD_CAPITAL: "إضافة رأس مال الشركة",
            NOMINAL_VALUE_OF_SHARE: "القيمة الاسمية للسهم",
            AUTHORIZED_CAPITAL_AMOUNT: "رأس المال المصرح به",
            PAID_CAPITAL_AMOUNT: "رأس المال المدفوع",
            ISSUED_SHARES: "الأسهم المصدرة",
            CLASS_OF_SHARES: "فئة الأسهم",
            CCI_NUMBER: "رقم غرفة التجارة",
            CCI_ISSUE_DATE: "تاريخ إصدار غرفة التجارة",
            CCI_ISSUE_DATE_REQUIRED: "تاريخ إصدار غرفة التجارة مطلوب",
            CCI_EXPIRY_DATE: "تاريخ انتهاء غرفة التجارة",
            CCI_USERNAME: "اسم مستخدم غرفة التجارة",
            CCI_PASSWORD: "كلمة مرور غرفة التجارة",
            CONTRACTS: "عقود الشركة",               // <-- Added
            ADD_CONTRACT: "إضافة عقد",              // <-- Added
            ADD_BOARD_MEMBER: "إضافة عضو مجلس إدارة", // <-- Added
            BANK_ACCOUNTS: "الحسابات البنكية",        // <-- Added
            ADD_BANK_ACCOUNT: "إضافة حساب بنكي",      // <-- Added
            CAPITAL_CURRENCY: "عملة رأس المال", // <-- Added
        },
        COMMON: {
            PERSON: "شخص",
            COMPANY: "شركة",
            ADD_COMPANY: "إضافة شركة",
            EMAIL_REQUIRED: "البريد الإلكتروني مطلوب",
            PHONE_REQUIRED: "رقم الهاتف مطلوب",
            ADDRESS_REQUIRED: "العنوان مطلوب",
            NO_FILE_SELECTED: "لم يتم اختيار ملف",
            UPLOAD_DOCUMENT: "رفع مستند",
            UPLOAD_FILE: "رفع ملف",
            VIEW_FILE: "عرض الملف",
            PHONE_TYPE: "نوع الهاتف",
            PHONE_TYPE_REQUIRED: "نوع الهاتف مطلوب",
            ID: "المعرف",
            ADD: "إضافة",
            EDIT: "تعديل",
            UPDATE: "تحديث",
            DELETE: "حذف",
            FILTERS: "الفلاتر",
            SEARCH: "بحث",
            PRINT: "طباعة",
            SELECTED: "مختار",
            ACTION: "إجراء",
            ACTIONS: "الإجراءات",
            PRIMARY: "أساسي",
            FILE_NAME: "اسم الملف",
            ADD_USER: "اضافة مستخدم",
            ADD_USERS: "اضافة المستخدمين",
            ADD_MENUS: "اضافة قائمة",
            SET_MENUS: "تعديل المجموعات",
            PUBLIC: "عام",
            EXPIRED: "منتهية",
            PRIVATE: "خاص",
            NEW: "جديد",
            ACTIVE: "نشط",
            INACTIVE: "غير نشط",
            IS_LD_STAFF: "هل موظف Ld",
            YES: "نعم",
            NO: "لا",
            ALL: "الكل",
            EXPORT: "تصدير",
            ACTIVATE: "تفعيل",
            DEACTIVATE: "إلغاء التفعيل",
            NATIONALITY: "الجنسية",
            RECORDS_RETURNED: "عدد السجلات المسترجعة",
            NO_RECORDS: "لا توجد سجلات",
            EDIT_COMPANY: "تعديل الشركة",
            MORE_ACTIONS: "مزيد من الإجراءات ",
            REMINDER: "تذكير",
            INC_DATE: "تاريخ التأسيس",
            FPC_CODE: "رمز FPC",
            LICENSE_NUMBER: "رقم الرخصة",
            ISSUE_DATE: "تاريخ الإصدار",
            EXPIRY_DATE: "تاريخ الانتهاء",
            MARK_PUBLIC: "تعيين كعام",
            MARK_PRIVATE: "تعيين كخاص",
            OVERVIEW: "نظرة عامة",
            CONTACTS: "جهات الاتصال",
            ASSETS: "الأصول",
            NOTES: "ملاحظات",
            SHORT_NAME: "الاسم المختصر",
            NAME_EN: "الاسم بالإنجليزية",
            NAME_AR: "الاسم بالعربية",
            SHOW: "إظهار",
            HIDE: "إخفاء",
            ADD_NOTE: "إضافة ملاحظة",
            EDIT_NOTE: "تعديل الملاحظة",
            DELETE_NOTE: "حذف الملاحظة",
            DATE: "التاريخ",
            STATUS: "الحالة",
            EMAIL_ADDRESSES: "عناوين البريد الإلكتروني",
            EMAIL_ADDRESS: "عنوان البريد الإلكتروني",
            ADD_EMAIL: "إضافة بريد إلكتروني",
            EDIT_EMAIL: "تعديل البريد الإلكتروني",
            DELETE_EMAIL: "حذف البريد الإلكتروني",
            PHONE_NUMBERS: "أرقام الهواتف",
            PHONE_NUMBER: "رقم الهاتف",
            ADD_PHONE: "إضافة هاتف",
            EDIT_PHONE: "تعديل الهاتف",
            DELETE_PHONE: "حذف الهاتف",
            ADD_ADDRESS: "إضافة عنوان",
            EDIT_ADDRESS: "تعديل العنوان",
            DELETE_ADDRESS: "حذف العنوان",
            ADDRESSES: "العناوين",
            CANCEL: "إلغاء",
            SAVE: "حفظ",
            SHORT_NAME_REQUIRED: "الاسم المختصر مطلوب",
            FIRST_NAME_AR_REQUIRED: "الاسم الأول (بالعربية) مطلوب",
            FIRST_NAME_EN_REQUIRED: "الاسم الأول (بالإنجليزية) مطلوب",
            ADD_NAME_EN: "إضافة الاسم بالإنجليزية",
            ADD_NAME_AR: "إضافة الاسم بالعربية",
            ADD_SHORT_NAME: "إضافة الاسم المختصر",
            NO_SPACES: "لا يمكن أن يحتوي على مسافات.",
            CITIES: "المدن",
            ADDRESS_LINE1: "سطر العنوان 1",
            ADDRESS_LINE2: "سطر العنوان 2",
            ADDRESS_LINE3: "سطر العنوان 3",
            ADDRESS_LINE1_PLACEHOLDER: "أدخل عنوان الشارع، رقم المبنى...",
            ADDRESS_LINE2_PLACEHOLDER: "أدخل الشقة، الجناح، الوحدة...",
            ADDRESS_LINE3_PLACEHOLDER: "أدخل تفاصيل إضافية للعنوان...",
            ADDRESS_LINE1_REQUIRED: "سطر العنوان 1 مطلوب",
            ADDRESS_LINE2_REQUIRED: "سطر العنوان 2 مطلوب",
            ADDRESS_LINE3_REQUIRED: "سطر العنوان 3 مطلوب",
            PO_BOX_NUMBER: "رقم صندوق البريد",
            PO_BOX_NUMBER_PLACEHOLDER: "أدخل رقم صندوق البريد...",
            PO_BOX_NUMBER_REQUIRED: "رقم صندوق البريد مطلوب",
            DATE_OF_APPOINTMENT: "تاريخ التعيين",
            RULE: "الدور",
            VIEW: "عرض",
            LOADING: "جاري التحميل...",               // <-- Added
            NOTE: "ملاحظة",
            NO_RESULTS_FOUND: "لم يتم العثور على نتائج",
            CONFIRM_DELETE: "تأكيد الحذف",
            CONFIRM: "تأكيد",
            CLOSE: "إغلاق",
            SUBMIT: "إرسال",
            OK: "موافق",
            SEARCH_BY_NAME: "البحث بالاسم",
            ADD_NEW_USER_GROUP: "إضافة مجموعة مستخدمين جديدة",
            ADD_NEW_MENU_ITEM: "إضافة عنصر قائمة جديد",
            ADD_GROUP_MENU: "إضافة قائمة المجموعة",
            EDIT_OTHER_DOCUMENT: "تعديل وثيقة أخرى",
            EDIT_ID_DOCUMENT: "تعديل وثيقة الهوية",
            USERNAME: "اسم المستخدم",
            LOGIN_NAME: "اسم الدخول",
            NT_LOGIN: "دخول NT",
            EMAIL: "البريد الإلكتروني",
            FIRST_NAME: "الاسم الأول",
            LAST_NAME: "الاسم الأخير",
            NAME: "الاسم",
            DESCRIPTION: "الوصف",
            SELECT: "اختيار",
            HOME: "الرئيسية",
            DASHBOARD: "لوحة القيادة",
            SETTINGS: "الإعدادات",
            USERS: "المستخدمون",
            GROUPS: "المجموعات",
            MENUS: "القوائم",
            REPORTS: "التقارير",
            USER_MANAGEMENT: "إدارة المستخدمين",
            GROUP_MANAGEMENT: "إدارة المجموعات",
            MENU_MANAGEMENT: "إدارة القوائم",
            DYNAMIC_LISTS: "القوائم الديناميكية",
            USER_GROUPS: "مجموعات المستخدمين",
            GROUP_MENUS: "قوائم المجموعات",
        },
    }
} as const;
